# fetching data from the apis

In [24]:
import pandas as pd
import requests

In [25]:
import requests
from requests.adapters import HTTPAdapter
from urllib3.util import Retry
session = requests.Session()

retries = Retry(
    total=5,
    backoff_factor=1,
    status_forcelist=[500, 502, 503, 504],
    raise_on_status=False
)
session.mount("http://", HTTPAdapter(max_retries=retries))
session.mount("https://", HTTPAdapter(max_retries=retries))

headers = {
    "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
}

url = "https://api.themoviedb.org/3/movie/top_rated?api_key=0fd2f27598db081a124de916fddc4812&language=en-US&page=1"

try:
    response = session.get(url, headers=headers, timeout=15)
    if response.status_code == 200:
        print("Success! Data retrieved.")
        data = response.json()
        print(f"Fetched {len(data.get('results', []))} movies.")
    else:
        print(f"API Error. Status Code: {response.status_code}")
        print(response.text)
except requests.exceptions.ConnectionError as e:
    print("The connection was still reset by TMDb after 5 retries:", e)

Success! Data retrieved.
Fetched 20 movies.

In [26]:
response.json()['results']

[{'adult': False,
  'backdrop_path': '/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg',
  'genre_ids': [35, 10749],
  'id': 1632181,
  'title': 'Accidental Partners',
  'original_language': 'es',
  'original_title': 'Socias por accidente',
  'overview': 'Two women discover they were both scammed by the same man (who also got them pregnant). They form an alliance to take revenge.',
  'popularity': 31.9745,
  'poster_path': '/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg',
  'release_date': '2026-03-12',
  'softcore': False,
  'video': False,
  'vote_average': 8.994,
  'vote_count': 324},
 {'adult': False,
  'backdrop_path': '/zMwhWailP1WY7sb6AoE6b8ugoy.jpg',
  'genre_ids': [12, 16, 10751, 14],
  'id': 1007757,
  'title': 'Swapped',
  'original_language': 'en',
  'original_title': 'Swapped',
  'overview': 'A small woodland creature and a majestic bird, two natural sworn enemies of the Valley, magically trade places and set off on an adventure of a lifetime to switch back. Their journey soon uncovers a greater threat—one that could endanger not only their species, but the entire valley they call home.',
  'popularity': 71.2324,
  'poster_path': '/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg',
  'release_date': '2026-05-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.9,
  'vote_count': 2005},
 {'adult': False,
  'backdrop_path': '/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg',
  'genre_ids': [18, 80],
  'id': 278,
  'title': 'The Shawshank Redemption',
  'original_language': 'en',
  'original_title': 'The Shawshank Redemption',
  'overview': 'Imprisoned in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.',
  'popularity': 99.7554,
  'poster_path': '/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
  'release_date': '1994-09-23',
  'softcore': False,
  'video': False,
  'vote_average': 8.726,
  'vote_count': 30853},
 {'adult': False,
  'backdrop_path': '/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg',
  'genre_ids': [10402, 18],
  'id': 936075,
  'title': 'Michael',
  'original_language': 'en',
  'original_title': 'Michael',
  'overview': 'The story of Michael Jackson, one of the most influential artists the world has ever known, and his life beyond the music. His journey from the discovery of his extraordinary talent as the lead of the Jackson Five, to the visionary artist whose creative ambition fueled a relentless pursuit to become the biggest entertainer in the world, highlighting both his life off-stage and some of the most iconic performances from his early solo career.',
  'popularity': 130.0099,
  'poster_path': '/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg',
  'release_date': '2026-04-22',
  'softcore': False,
  'video': False,
  'vote_average': 8.695,
  'vote_count': 3728},
 {'adult': False,
  'backdrop_path': '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
  'genre_ids': [18, 80],
  'id': 238,
  'title': 'The Godfather',
  'original_language': 'en',
  'original_title': 'The Godfather',
  'overview': 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers, launching a campaign of bloody revenge.',
  'popularity': 52.0454,
  'poster_path': '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
  'release_date': '1972-03-14',
  'softcore': False,
  'video': False,
  'vote_average': 8.687,
  'vote_count': 23214},
 {'adult': False,
  'backdrop_path': '/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg',
  'genre_ids': [878, 12],
  'id': 687163,
  'title': 'Project Hail Mary',
  'original_language': 'en',
  'original_title': 'Project Hail Mary',
  'overview': 'Science teacher Ryland Grace wakes up on a spaceship light years from home with no recollection of who he is or how he got there. As his memory returns, he begins to uncover his mission: solve the riddle of the mysterious substance causing the sun to die out. He must call on his scientific knowledge and unorthodox ideas to save everything on Earth from extinction.',
  'popularity': 201.2387,
  'poster_path': '/yihdXomYb5kTeSivtFndMy5iDmf.jpg',
  'release_date': '2026-03-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.66,
  'vote_count': 6475},
 {'adult': False,
  'backdrop_path': '/kGzFbGhp99zva6oZODW5atUtnqi.jpg',
  'genre_ids': [18, 80],
  'id': 240,
  'title': 'The Godfather Part II',
  'original_language': 'en',
  'original_title': 'The Godfather Part II',
  'overview': 'In the continuing saga of the Corleone crime family, a young Vito Corleone grows up in Sicily and in 1910s New York. In the 1950s, Michael Corleone attempts to expand the family business into Las Vegas, Hollywood and Cuba.',
  'popularity': 31.1927,
  'poster_path': '/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg',
  'release_date': '1974-12-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.571,
  'vote_count': 14087},
 {'adult': False,
  'backdrop_path': '/zb6fM1CX41D9rF9hdgclu0peUmy.jpg',
  'genre_ids': [18, 36, 10752],
  'id': 424,
  'title': "Schindler's List",
  'original_language': 'en',
  'original_title': "Schindler's List",
  'overview': 'The true story of how businessman Oskar Schindler saved over a thousand Jewish lives from the Nazis while they worked as slaves in his factory during World War II.',
  'popularity': 29.2549,
  'poster_path': '/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg',
  'release_date': '1993-12-15',
  'softcore': False,
  'video': False,
  'vote_average': 8.57,
  'vote_count': 17644},
 {'adult': False,
  'backdrop_path': '/qqHQsStV6exghCM7zbObuYBiYxw.jpg',
  'genre_ids': [18],
  'id': 389,
  'title': '12 Angry Men',
  'original_language': 'en',
  'original_title': '12 Angry Men',
  'overview': "The defense and the prosecution have rested and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father. What begins as an open and shut case soon becomes a mini-drama of each of the jurors' prejudices and preconceptions about the trial, the accused, and each other.",
  'popularity': 24.8318,
  'poster_path': '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
  'release_date': '1957-04-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.565,
  'vote_count': 10153},
 {'adult': False,
  'backdrop_path': '/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg',
  'genre_ids': [16, 10751, 14],
  'id': 129,
  'title': 'Spirited Away',
  'original_language': 'ja',
  'original_title': '千と千尋の神隠し',
  'overview': 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free her family.',
  'popularity': 31.7959,
  'poster_path': '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
  'release_date': '2001-07-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 18589},
 {'adult': False,
  'backdrop_path': '/dqK9Hag1054tghRQSqLSfrkvQnA.jpg',
  'genre_ids': [28, 80, 53],
  'id': 155,
  'title': 'The Dark Knight',
  'original_language': 'en',
  'original_title': 'The Dark Knight',
  'overview': 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets. The partnership proves to be effective, but they soon find themselves prey to a reign of chaos unleashed by a rising criminal mastermind known to the terrified citizens of Gotham as the Joker.',
  'popularity': 57.5176,
  'poster_path': '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
  'release_date': '2008-07-16',
  'softcore': False,
  'video': False,
  'vote_average': 8.534,
  'vote_count': 36184},
 {'adult': False,
  'backdrop_path': '/84beTJf26mfhoasUlKSOiNSutyS.jpg',
  'genre_ids': [35, 18, 10749],
  'id': 19404,
  'title': 'Dilwale Dulhania Le Jayenge',
  'original_language': 'hi',
  'original_title': 'दिलवाले दुल्हनिया ले जायेंगे',
  'overview': 'Raj is a rich, carefree, happy-go-lucky second generation NRI. Simran is the daughter of Chaudhary Baldev Singh, who in spite of being an NRI is very strict about adherence to Indian values. Simran has left for India to be married to her childhood fiancé. Raj leaves for India with a mission at his hands, to claim his lady love under the noses of her whole family. Thus begins a saga.',
  'popularity': 12.6291,
  'poster_path': '/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg',
  'release_date': '1995-10-20',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 4602},
 {'adult': False,
  'backdrop_path': '/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg',
  'genre_ids': [14, 18, 80],
  'id': 497,
  'title': 'The Green Mile',
  'original_language': 'en',
  'original_title': 'The Green Mile',
  'overview': "A supernatural tale set on death row in a Southern prison, where gentle giant John Coffey possesses the mysterious power to heal people's ailments. When the cell block's head guard, Paul Edgecomb, recognizes Coffey's miraculous gift, he tries desperately to help stave off the condemned man's execution.",
  'popularity': 36.9016,
  'poster_path': '/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg',
  'release_date': '1999-12-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.5,
  'vote_count': 19488},
 {'adult': False,
  'backdrop_path': '/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg',
  'genre_ids': [12, 14, 28],
  'id': 122,
  'title': 'The Lord of the Rings: The Return of the King',
  'original_language': 'en',
  'original_title': 'The Lord of the Rings: The Return of the King',
  'overview': 'As armies mass for a final battle that will decide the fate of the world--and powerful, ancient forces of Light and Dark compete to determine the outcome--one member of the Fellowship of the Ring is revealed as the noble heir to the throne of the Kings of Men. Yet, the sole hope for triumph over evil lies with a brave hobbit, Frodo, who, accompanied by his loyal friend Sam and the hideous, wretched Gollum, ventures deep into the very dark heart of Mordor on his seemingly impossible quest to destroy the Ring of Power.\u200b',
  'popularity': 47.2977,
  'poster_path': '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
  'release_date': '2003-12-17',
  'softcore': False,
  'video': False,
  'vote_average': 8.502,
  'vote_count': 26917},
 {'adult': False,
  'backdrop_path': '/bVGHSe47W6oCQL1Q88pvRAet51A.jpg',
  'genre_ids': [18, 9648],
  'id': 1330021,
  'title': 'Remarkably Bright Creatures',
  'original_language': 'en',
  'original_title': 'Remarkably Bright Creatures',
  'overview': 'Through unlikely bonds formed during night shifts at a local aquarium, Tova, an elderly widow, learns of a life-changing discovery that may bring her joy and wonder once again.',
  'popularity': 31.9834,
  'poster_path': '/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg',
  'release_date': '2026-05-07',
  'softcore': False,
  'video': False,
  'vote_average': 8.494,
  'vote_count': 777},
 {'adult': False,
  'backdrop_path': '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
  'genre_ids': [35, 53, 18],
  'id': 496243,
  'title': 'Parasite',
  'original_language': 'ko',
  'original_title': '기생충',
  'overview': "All unemployed, Ki-taek's family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.",
  'popularity': 34.4576,
  'poster_path': '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
  'release_date': '2019-05-30',
  'softcore': False,
  'video': False,
  'vote_average': 8.49,
  'vote_count': 20932},
 {'adult': False,
  'backdrop_path': '/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg',
  'genre_ids': [35, 10749],
  'id': 1181678,
  'title': '¿Quieres ser mi hijo?',
  'original_language': 'en',
  'original_title': '¿Quieres ser mi hijo?',
  'overview': 'Lu, a conformist woman in her forties, learns that her 15-year partner has been having extramarital affairs. Starting from scratch, she gets involved in an unexpected relationship with a young womanizer.',
  'popularity': 11.1149,
  'poster_path': '/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg',
  'release_date': '2023-09-21',
  'softcore': False,
  'video': False,
  'vote_average': 8.479,
  'vote_count': 358},
 {'adult': False,
  'backdrop_path': '/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg',
  'genre_ids': [12, 18, 878],
  'id': 157336,
  'title': 'Interstellar',
  'original_language': 'en',
  'original_title': 'Interstellar',
  'overview': 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
  'popularity': 78.7607,
  'poster_path': '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
  'release_date': '2014-11-05',
  'softcore': False,
  'video': False,
  'vote_average': 8.483,
  'vote_count': 40449},
 {'adult': False,
  'backdrop_path': '/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg',
  'genre_ids': [16, 10749, 18],
  'id': 372058,
  'title': 'Your Name.',
  'original_language': 'ja',
  'original_title': '君の名は。',
  'overview': 'High schoolers Mitsuha and Taki are complete strangers living separate lives. But one night, they suddenly switch places. Mitsuha wakes up in Taki’s body, and he in hers. This bizarre occurrence continues to happen randomly, and the two must adjust their lives around each other.',
  'popularity': 23.6876,
  'poster_path': '/q719jXXEzOoYaps6babgKnONONX.jpg',
  'release_date': '2016-07-01',
  'softcore': False,
  'video': False,
  'vote_average': 8.481,
  'vote_count': 12725},
 {'adult': False,
  'backdrop_path': '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
  'genre_ids': [53, 80, 35],
  'id': 680,
  'title': 'Pulp Fiction',
  'original_language': 'en',
  'original_title': 'Pulp Fiction',
  'overview': "A burger-loving hit man, his philosophical partner, a drug-addled gangster's moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.",
  'popularity': 38.8723,
  'poster_path': '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
  'release_date': '1994-09-10',
  'softcore': False,
  'video': False,
  'vote_average': 8.482,
  'vote_count': 30489}]

In [27]:
pd.DataFrame(response.json()['results'])

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/iCML6fBe3X0y06P33bM7dyYXPKZ.jpg,"[35, 10749]",1632181,Accidental Partners,es,Socias por accidente,Two women discover they were both scammed by t...,31.9745,/j0CIVzeR7hRAPBPGR54qDZoOQpp.jpg,2026-03-12,False,False,8.994,324
1,False,/zMwhWailP1WY7sb6AoE6b8ugoy.jpg,"[12, 16, 10751, 14]",1007757,Swapped,en,Swapped,"A small woodland creature and a majestic bird,...",71.2324,/tHhxWxge06goXU6ZQH1hj7vK8Hd.jpg,2026-05-01,False,False,8.900,2005
2,False,/zfbjgQE1uSd9wiPTX4VzsLi0rGG.jpg,"[18, 80]",278,The Shawshank Redemption,en,The Shawshank Redemption,Imprisoned in the 1940s for the double murder ...,99.7554,/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg,1994-09-23,False,False,8.726,30853
3,False,/ufSwlnECLoUbBjPrFqEQcWBzHwc.jpg,"[10402, 18]",936075,Michael,en,Michael,"The story of Michael Jackson, one of the most ...",130.0099,/zm0KAbOjlt9eR5y7vDiL2dEOwMl.jpg,2026-04-22,False,False,8.695,3728
4,False,/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg,"[18, 80]",238,The Godfather,en,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",52.0454,/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,1972-03-14,False,False,8.687,23214
5,False,/2I1OFQJ0L9T0dpU6FobKFWV2PxX.jpg,"[878, 12]",687163,Project Hail Mary,en,Project Hail Mary,Science teacher Ryland Grace wakes up on a spa...,201.2387,/yihdXomYb5kTeSivtFndMy5iDmf.jpg,2026-03-15,False,False,8.660,6475
6,False,/kGzFbGhp99zva6oZODW5atUtnqi.jpg,"[18, 80]",240,The Godfather Part II,en,The Godfather Part II,In the continuing saga of the Corleone crime f...,31.1927,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,1974-12-20,False,False,8.571,14087
7,False,/zb6fM1CX41D9rF9hdgclu0peUmy.jpg,"[18, 36, 10752]",424,Schindler's List,en,Schindler's List,The true story of how businessman Oskar Schind...,29.2549,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,1993-12-15,False,False,8.570,17644
8,False,/qqHQsStV6exghCM7zbObuYBiYxw.jpg,[18],389,12 Angry Men,en,12 Angry Men,The defense and the prosecution have rested an...,24.8318,/ppd84D2i9W8jXmsyInGyihiSyqz.jpg,1957-04-10,False,False,8.565,10153
9,False,/dyJvKsNs2KP8qQnAXbRwDjblViy.jpg,"[16, 10751, 14]",129,Spirited Away,ja,千と千尋の神隠し,"A young girl, Chihiro, becomes trapped in a st...",31.7959,/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg,2001-07-20,False,False,8.534,18589
10,False,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[28, 80, 53]",155,The Dark Knight,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,57.5176,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,False,False,8.534,36184
11,False,/84beTJf26mfhoasUlKSOiNSutyS.jpg,"[35, 18, 10749]",19404,Dilwale Dulhania Le Jayenge,hi,दिलवाले दुल्हनिया ले जायेंगे,"Raj is a rich, carefree, happy-go-lucky second...",12.6291,/tFbfCkS7q6g96wVoAu8kyr93iPm.jpg,1995-10-20,False,False,8.500,4602
12,False,/b6HWTOxn1xevvyHU2K9ICvaRU6g.jpg,"[14, 18, 80]",497,The Green Mile,en,The Green Mile,A supernatural tale set on death row in a Sout...,36.9016,/8VG8fDNiy50H4FedGwdSVUPoaJe.jpg,1999-12-10,False,False,8.500,19488
13,False,/2u7zbn8EudG6kLlBzUYqP8RyFU4.jpg,"[12, 14, 28]",122,The Lord of the Rings: The Return of the King,en,The Lord of the Rings: The Return of the King,As armies mass for a final battle that will de...,47.2977,/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg,2003-12-17,False,False,8.502,26917
14,False,/bVGHSe47W6oCQL1Q88pvRAet51A.jpg,"[18, 9648]",1330021,Remarkably Bright Creatures,en,Remarkably Bright Creatures,Through unlikely bonds formed during night shi...,31.9834,/9HcEqn3D4J6b2Z0jK54id9nA0fr.jpg,2026-05-07,False,False,8.494,777
15,False,/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg,"[35, 53, 18]",496243,Parasite,ko,기생충,"All unemployed, Ki-taek's family takes peculia...",34.4576,/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg,2019-05-30,False,False,8.490,20932
16,False,/xyWKrni8WrYzqn7ztvI5nIY0h62.jpg,"[35, 10749]",1181678,¿Quieres ser mi hijo?,en,¿Quieres ser mi hijo?,"Lu, a conformist woman in her forties, learns ...",11.1149,/6PQJsmuvSMZQMmlJfTpjIkrizUh.jpg,2023-09-21,False,False,8.479,358
17,False,/5XNQBqnBwPA9yT0jZ0p3s8bbLh0.jpg,"[12, 18, 878]",157336,Interstellar,en,Interstellar,The adventures of a group of explorers who mak...,78.7607,/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg,2014-11-05,False,False,8.483,40449
18,False,/mMtUybQ6hL24FXo0F3Z4j2KG7kZ.jpg,"[16, 10749, 18]",372058,Your Name.,ja,君の名は。,High schoolers Mitsuha and Taki are complete s...,23.6876,/q719jXXEzOoYaps6babgKnONONX.jpg,2016-07-01,False,False,8.481,12725
19,False,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80, 35]",680,Pulp Fiction,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",38.8723,/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg,1994-09-10,False,False,8.482,30489

In [28]:
df = pd.DataFrame(response.json()['results'])[[
    'id', 'overview', 'title', 'release_date', 
    'popularity', 'vote_average', 'vote_count'
]]

In [29]:
df

,id,overview,title,release_date,popularity,vote_average,vote_count
0,1632181,Two women discover they were both scammed by t...,Accidental Partners,2026-03-12,31.9745,8.994,324
1,1007757,"A small woodland creature and a majestic bird,...",Swapped,2026-05-01,71.2324,8.900,2005
2,278,Imprisoned in the 1940s for the double murder ...,The Shawshank Redemption,1994-09-23,99.7554,8.726,30853
3,936075,"The story of Michael Jackson, one of the most ...",Michael,2026-04-22,130.0099,8.695,3728
4,238,"Spanning the years 1945 to 1955, a chronicle o...",The Godfather,1972-03-14,52.0454,8.687,23214
5,687163,Science teacher Ryland Grace wakes up on a spa...,Project Hail Mary,2026-03-15,201.2387,8.660,6475
6,240,In the continuing saga of the Corleone crime f...,The Godfather Part II,1974-12-20,31.1927,8.571,14087
7,424,The true story of how businessman Oskar Schind...,Schindler's List,1993-12-15,29.2549,8.570,17644
8,389,The defense and the prosecution have rested an...,12 Angry Men,1957-04-10,24.8318,8.565,10153
9,129,"A young girl, Chihiro, becomes trapped in a st...",Spirited Away,2001-07-20,31.7959,8.534,18589
10,155,Batman raises the stakes in his war on crime. ...,The Dark Knight,2008-07-16,57.5176,8.534,36184
11,19404,"Raj is a rich, carefree, happy-go-lucky second...",Dilwale Dulhania Le Jayenge,1995-10-20,12.6291,8.500,4602
12,497,A supernatural tale set on death row in a Sout...,The Green Mile,1999-12-10,36.9016,8.500,19488
13,122,As armies mass for a final battle that will de...,The Lord of the Rings: The Return of the King,2003-12-17,47.2977,8.502,26917
14,1330021,Through unlikely bonds formed during night shi...,Remarkably Bright Creatures,2026-05-07,31.9834,8.494,777
15,496243,"All unemployed, Ki-taek's family takes peculia...",Parasite,2019-05-30,34.4576,8.490,20932
16,1181678,"Lu, a conformist woman in her forties, learns ...",¿Quieres ser mi hijo?,2023-09-21,11.1149,8.479,358
17,157336,The adventures of a group of explorers who mak...,Interstellar,2014-11-05,78.7607,8.483,40449
18,372058,High schoolers Mitsuha and Taki are complete s...,Your Name.,2016-07-01,23.6876,8.481,12725
19,680,"A burger-loving hit man, his philosophical par...",Pulp Fiction,1994-09-10,38.8723,8.482,30489

In [30]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [ ]:
import pandas as pd
import requests
from requests.adapters import HTTPAdapter
from urllib3.util import Retry

# Your TMDb API key
API_KEY = "YOUR_ACTUAL_API_KEY"

# Create session
session = requests.Session()

retries = Retry(
    total=5,
    backoff_factor=1,
    status_forcelist=[429, 500, 502, 503, 504],
    allowed_methods=["GET"],
    raise_on_status=False
)

session.mount(
    "https://",
    HTTPAdapter(max_retries=retries)
)

headers = {
    "accept": "application/json"
}

all_movies = []

for page in range(1, 5):

    url = "https://api.themoviedb.org/3/movie/popular"

    params = {
        "api_key": '0fd2f27598db081a124de916fddc4812',      
        "language": "en-US",
        "page": page
    }

    try:

        response = session.get(
            url,
            headers=headers,
            params=params,
            timeout=15
        )

        if response.status_code == 200:

            data = response.json()

            results = data.get("results", [])

            print(
                f"Page {page}: Success! "
                f"Fetched {len(results)} movies."
            )

            all_movies.extend(results)

        else:

            print(
                f"Page {page}: API Error. "
                f"Status Code: {response.status_code}"
            )

            print(response.text)

    except requests.exceptions.RequestException as e:

        print(
            f"Page {page}: Request failed: {e}"
        )


# Create DataFrame
df = pd.DataFrame(all_movies)

print(
    f"\nFinal DataFrame created with "
    f"{len(df)} total rows."
)

print("\nFirst 5 movies:")
print(df.head())

Page 1: Success! Fetched 20 movies.
Page 2: Success! Fetched 20 movies.
Page 3: Success! Fetched 20 movies.
Page 4: Success! Fetched 20 movies.

Final DataFrame created with 80 total rows.

First 5 movies:
   adult                     backdrop_path            genre_ids       id  \
0  False   /RMXG8myu1aGlNUsRjtxzmpdMK0.jpg         [12, 28, 14]  1368337
1  False  /pW4Ah1A6SgZNQNmf5AgiIYPzFHF.jpg            [878, 53]  1275779
2  False  /piV2OnzTZCyGBP9JCjlHIgKGlfo.jpg        [28, 14, 878]   454639
3  False  /c6BPbkO5Npt1OdwttAxCFo06wtH.jpg  [10751, 14, 35, 12]  1108427
4  False  /r013C8Me2bZ0pUi0OWJRh0h7MzT.jpg             [27, 53]  1339713

                     title original_language           original_title  \
0              The Odyssey                en              The Odyssey
1           Disclosure Day                en           Disclosure Day
2  Masters of the Universe                en  Masters of the Universe
3                    Moana                en                    Moana
4                Obsession                en                Obsession

                                            overview  popularity  \
0  Odysseus, the legendary King of Ithaca, embark...   1049.7104
1  A cybersecurity expert becomes a whistleblower...    596.4318
2  After being separated for 15 years, the Sword ...    539.6908
3  Teenage Moana answers the Ocean's call and, fo...    519.3627
4  After breaking the mysterious "One Wish Willow...    401.1034

                        poster_path release_date  softcore  video  \
0  /5rhTDKUhPYvpdQIijFIs5VoWsON.jpg   2026-07-15     False  False
1  /AnJ8IQJI23hNpYXVNaythu061Ru.jpg   2026-06-10     False  False
2  /oRuyGUHdoaQxWP3SDfafGkStxTC.jpg   2026-06-03     False  False
3  /zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg   2026-07-08     False  False
4  /bRwnj8WEKBCvmfeUNOukJPwB43K.jpg   2026-05-13     False  False

   vote_average  vote_count
0         7.966        1547
1         7.382        1826
2         7.345        1140
3         5.900         145
4         8.300        3753

In [36]:
df

,adult,backdrop_path,genre_ids,id,title,original_language,original_title,overview,popularity,poster_path,release_date,softcore,video,vote_average,vote_count
0,False,/RMXG8myu1aGlNUsRjtxzmpdMK0.jpg,"[12, 28, 14]",1368337,The Odyssey,en,The Odyssey,"Odysseus, the legendary King of Ithaca, embark...",1049.7104,/5rhTDKUhPYvpdQIijFIs5VoWsON.jpg,2026-07-15,False,False,7.966,1547
1,False,/pW4Ah1A6SgZNQNmf5AgiIYPzFHF.jpg,"[878, 53]",1275779,Disclosure Day,en,Disclosure Day,A cybersecurity expert becomes a whistleblower...,596.4318,/AnJ8IQJI23hNpYXVNaythu061Ru.jpg,2026-06-10,False,False,7.382,1826
2,False,/piV2OnzTZCyGBP9JCjlHIgKGlfo.jpg,"[28, 14, 878]",454639,Masters of the Universe,en,Masters of the Universe,"After being separated for 15 years, the Sword ...",539.6908,/oRuyGUHdoaQxWP3SDfafGkStxTC.jpg,2026-06-03,False,False,7.345,1140
3,False,/c6BPbkO5Npt1OdwttAxCFo06wtH.jpg,"[10751, 14, 35, 12]",1108427,Moana,en,Moana,"Teenage Moana answers the Ocean's call and, fo...",519.3627,/zKVgiv5qHCvCLT4A2ymJi5QeXDH.jpg,2026-07-08,False,False,5.900,145
4,False,/r013C8Me2bZ0pUi0OWJRh0h7MzT.jpg,"[27, 53]",1339713,Obsession,en,Obsession,"After breaking the mysterious ""One Wish Willow...",401.1034,/bRwnj8WEKBCvmfeUNOukJPwB43K.jpg,2026-05-13,False,False,8.300,3753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,False,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"[878, 28, 12]",24428,The Avengers,en,The Avengers,When an unexpected enemy emerges and threatens...,54.7596,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,False,False,8.059,38885
76,False,/7yLkJLqLfrCaQvR97AF1Gmd4nQN.jpg,[27],1631506,The Hanged Woman,es,La ahorcada,"Rosa Martín, a singer-songwriter known as La A...",67.5226,/j5016vxLjYd5pmXezXNHYTbsjro.jpg,2026-04-22,False,False,5.200,4
77,False,/lgotja3xMoJZbynwHfcQcJAEMWH.jpg,"[16, 12, 35, 9648, 10751]",1084242,Zootopia 2,en,Zootopia 2,After cracking the biggest case in Zootopia's ...,42.6724,/oJ7g2CifqpStmoYQyaLQgEU32qO.jpg,2025-11-26,False,False,7.684,3159
78,False,/7OjUOEWRoASbsmngmS96CpYfH3C.jpg,"[27, 36]",1301310,Zombies of the Third Reich,en,Zombies of the Third Reich,"During WW2, a group of assembled allied forces...",52.0615,/hjrgOWoruk9ea0tXaN8l2gtmkeH.jpg,2025-06-10,False,False,4.100,5
79,False,/kXXveIklCvTpJOGu16dszmZrcwD.jpg,"[36, 18]",1305672,I Know Who You Are,zh,抓特务,"On 1949 October 1, the day of the founding cer...",47.2045,/dzS3PxisVd9y9BrLPiFfA2MvcI8.jpg,2026-06-19,False,False,6.200,5

In [37]:
df.shape

(80, 15)

In [38]:
df.to_csv('movies.csv') # we can export api fetched dataframe to csv file